### ISSUE TITLE
/trigger command doesn't work

### ISSUE THREAD

**Issue by rafitamolin** [xabbo/xabbo#10]
Version: `v1.1.1`

When you type `/trigger`, nothing happens.

**Comment by b7c** [comment]
looks like this is not possible anymore without re-entering the room

**Comment by rafitamolin** [comment]
> looks like this is not possible anymore without re-entering the room

ohh i see, but it still works with the old version available in the gearth extension store

**Comment by b7c** [comment]
are you sure? it doesn't do anything for me on v1.0.3 either

**Comment by rafitamolin** [comment]
it works for me in the ES hotel with version 1.0.3

https://github.com/user-attachments/assets/2dec550b-954b-4ac6-9e9e-a9ae6c2d5a62

**Comment by b7c** [comment]
it was supposed to trigger the "user enters room" wired stack, so if the stack had "teleport to furni" then you could retrigger the teleport without re-entering the room, but it doesn't seem to work anymore

**Comment by rafitamolin** [comment]
> it was supposed to trigger the "user enters room" wired stack, so if the stack had "teleport to furni" then you could retrigger the teleport without re-entering the room, but it doesn't seem to work anymore

ohhh i see, my use case for it was to see the green friend tags again and to clear all the chat bubbles haha

**Comment by b7c** [comment]
oh lol I will probably rename the command to `/refresh` in that case when I fix the outgoing packet
