### ISSUE TITLE
Microsoft .NET

### ISSUE THREAD

**Issue by JoaoVitorJJV** [xabbo/xabbo#2]
The link of the microsoft .net informed in the apllication is incorret. If you go down, you'll down the RUNTIME. The correct is this: https://dotnet.microsoft.com/en-us/download/dotnet/5.0 (The SDK of 5.0, not RUNTIME)

**Comment by b7c** [comment]
The dialog that prompts you to install the correct runtime is shown by the .NET apphost, you will need to install the .NET Desktop Runtime 5.0.17 to run Xabbo v1.0.3.

**Comment by JoaoVitorJJV** [comment]
> The dialog that prompts you to install the correct runtime is shown by the .NET apphost, you will need to install the .NET Desktop Runtime 5.0.17 to run Xabbo v1.0.3.

I installed the runtime and dosen't work, just with SDK 5.0

**Comment by b7c** [comment]
I'll have to test with a clean environment if I have time, but I'll be updating the project to .NET 6 soon

**Comment by b7c** [comment]
v1.1.0 now uses the .NET 8 Runtime
