### ISSUE TITLE
/find command fails when executed twice in a row, if less than 5 seconds have elapsed

### ISSUE THREAD

**Issue by rafitamolin** [xabbo/xabbo#3]
The /find command fails when doing the following:

1. Type /find [friend] and receive the expected result.
2. If you type /find [friend] again, regardless of whether you choose the same friend or a different one, within 5 seconds after you first executed the command, the command fails.

![](https://i.imgur.com/8nVQZUv.png)

**Comment by b7c** [comment]
Thanks I was aware of this, it's due to the rate limiting of the `FollowFriend` packet. Will probably need to implement a queue so it doesn't hit the rate limit.

**Comment by b7c** [comment]
Fixed in v1.1.0
